config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :consultations, only:[:new,:create, :index, :show] do
    resources :litigantes, only:[:index]
  end
  resources :contactos, only:[:new, :create]
  resources :suscriptions, only: [:index, :show]


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController

skip_before_action :authenticate_user!

  def new
    @contacto = Contacto.new


  end

  def create
    @contacto= Contacto.create(contacto_params)
    redirect_to root_path

  end

private

  def contacto_params
    params.require(:contacto).permit(:name, :email, :text)
  end


end

app/views/contactos/new.html.erb
<h2>Contáctanos</h2>

<div class="container devise-form">

<%= simple_form_for(@contacto, url: contactos_path(@contacto), data: {turbo: false} ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name,
                required: false,
                autofocus: true,
                input_html: { autocomplete: "name" }%>
    <%= f.input :email,
                required: false,
                input_html: { autocomplete: "email" } %>
    <%= f.input :text,
                as: :text,
                required: false,
                :input_html => { 'rows' => 5, 'cols' => 10 } %>
  </div>

  <div class="form-actions btn-log">
    <%= f.button :submit, "Send" %>
  </div>
<% end %>

</div>