config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :consultations, only:[:new,:create, :index, :show] do
    resources :litigantes, only:[:index]
  end
  resources :contactos, only:[:new, :create]
  resources :suscriptions, only: [:index, :show]


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user
  has_many :demandas
end

app/controllers/consultations_controller.rb
require "open-uri"
require "json"
require "http"



class ConsultationsController < ApplicationController


  before_action :set_consultation, only: %i[ new create ]


  def index
    @user= current_user
    @consultations= policy_scope(Consultation).all
    @consultations= @user.consultation
    @consultation= Consultation.new
  end

  def show

    @consultation = Consultation.find(params[:id])
    authorize @consultation
    @demandas = @consultation.demandas
    @consultation= Consultation.new
  end

  def new
    @consultation= Consultation.new
    authorize @consultation
  end

  def create
    authorize @consultation
    conn = Faraday.new(
      url: 'https://api.sheriffqa.keiron.cl',
      headers: {   accept: "aplication/json",
        Authorization: ENV["KEY"]}
    )

    response = conn.get("https://prod.api.thesheriff.cl/api/v1/integration/helper/judicial/#{consultation_params[:rut]}")
    data = JSON.parse(response.body)

    if data["success"]
      @consultation = Consultation.create(rut: "#{data["data"]["rut"]}", nombre: "", user: current_user)
        data["data"]["civil"].each do |civil|
        @demanda = Demanda.create(
            consultation: @consultation,
            tipo: "civil",
            estado: "#{civil["estado"]}",
            estadoCausa: "#{civil["estadoCausa"]}",
            etapa: "#{civil["etapa"]}",
            fechaingreso:  "#{civil["fechaIngreso"]}",
            link: "#{civil["link"]}",
            linkPdf:  "#{civil["linkPdf"]}",
            LinkEbook:"#{civil["linkEbook"]}",
            proc: "#{civil["proc"]}",
            rol: "#{civil["rol"]}",
            tribunal: "#{civil["tribunal"]}"
          )
          civil["litigantes"].each do |litigante|
            @litigante = Litigante.create(
              demanda: @demanda,
              rut: "#{litigante["rut"]}",
              nombre: "#{litigante["nombre"]}",
              sujeto: "#{litigante["sujeto"]}",
              persona: "#{litigante["persona:"]}"
            )
          end
        end

          data["data"]["laboral"].each do |laboral|
            @demanda = Demanda.create(
              consultation: @consultation,
              tipo: "laboral",
              estado: "#{laboral["estado"]}",
              estadoCausa: "#{laboral["estadoCausa"]}",
              etapa: "#{laboral["etapa"]}",
              fechaingreso:  "#{laboral["fechaIngreso"]}",
              link: "#{laboral["link"]}",
              linkPdf:  "#{laboral["linkPdf"]}",
              LinkEbook:"#{laboral["linkEbook"]}",
              proc: "#{laboral["materia"]}",
              rol: "#{laboral["rit"]}",
              tribunal: "#{laboral["tribunal"]}"
          )
            laboral["litigantes"].each do |litigante|
              @litigante = Litigante.create(
                demanda: @demanda,
                rut: "#{litigante["rut"]}",
                nombre: "#{litigante["nombre"]}",
                sujeto: "#{litigante["sujeto"]}",
                persona: "#{litigante["persona:"]}"
              )
            end
        end

        data["data"]["cobranza"].each do |cobranza|
          @demanda = Demanda.create(
            consultation: @consultation,
            tipo: "cobranza",
            estado: "#{cobranza["estado"]}",
            estadoCausa: "#{cobranza["estadoCausa"]}",
            etapa: "#{cobranza["etapa"]}",
            fechaingreso:  "#{cobranza["fechaIngreso"]}",
            link: "#{cobranza["link"]}",
            linkPdf:  "#{cobranza["linkPdf"]}",
            LinkEbook:"#{cobranza["linkEbook"]}",
            proc: "#{cobranza["proc"]}",
            rol: "#{cobranza["rit"]}",
            tribunal: "#{cobranza["tribunal"]}"

        )
        cobranza["litigantes"].each do |litigante|
          @litigante = Litigante.create(
            demanda: @demanda,
            rut: "#{litigante["rut"]}",
            nombre: "#{litigante["nombre"]}",
            sujeto: "#{litigante["sujeto"]}",
            persona: "#{litigante["persona:"]}"
          )
        end

      end
   end

   @litigantes= Litigante.all
   @dueño = @litigantes.select do |litigante|
     litigante.rut == consultation_params[:rut]
   end
   @edit= Consultation.last
   if @dueño.empty?
    @edit.nombre = "Sin Demandas"
    @edit.save
    redirect_to consultations_path
   else
    @edit.nombre= @dueño.last.nombre
    @edit.save
    redirect_to consultations_path
  end


end



  private

  def consultation_params
    params.require(:consultation).permit(:rut, :id)
  end

  def set_consultation
    @consultation = Consultation.new
  end
end

app/views/consultations/index.html.erb
<div id="display">
  <div class="vertical">
    <%= render "shared/vertical" %>
  </div>

  <div class="show-consultas">
    <h2 style="font-size: 36px;padding-top:10px;padding-bottom: 5px;">Consultas:</h2>

        <% @consultations.each do | consultation|  %>

            <% civil_num = consultation.demandas.count { |element| element.tipo.match("civil") } %>
            <% laboral_num = consultation.demandas.count { |element| element.tipo.match("laboral") } %>
            <% cobranza_num = consultation.demandas.count { |element| element.tipo.match("cobranza") } %>
            <div class="card-trip">
              <div class="card-trip-infos" style="padding-top: 5px!">
                  <h2 class="w-25" style="font-size: 24px;padding-top: 0px;padding-left: 20px">  <%= consultation.nombre.capitalize %>  </h2>
                  <h2 style="font-size: 24px;padding-top: 0px;"> <%= consultation.rut %></h2>
                  <% if laboral_num > 1 && laboral_num <2 %>
                    <h2 style="font-size: 24px;padding-top:5px">Laboral:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #fbc02d"> <%= laboral_num %></h2>
                  <% end %>
                  <% if laboral_num > 2 %>
                    <h2 style="font-size: 24px;padding-top:5px">Laboral:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #b71c1c"> <%= laboral_num %></h2>
                  <% end %>
                  <% if laboral_num < 1 %>
                    <h2 style="font-size: 24px;padding-top: 5px">Laboral:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #388e3c"> <%= laboral_num %></h2>
                  <% end %>
                  <% if civil_num == 3 && civil_num <4 %>
                    <h2 style="font-size: 24px;padding-top: 5px">civil:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #fbc02d"> <%= civil_num %></h2>
                  <% end %>
                  <% if civil_num > 4 %>
                    <h2 style="font-size: 24px;padding-top: 5px">civil:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #b71c1c"> <%= civil_num %></h2>
                  <% end %>
                  <% if civil_num <= 2 %>
                    <h2 style="font-size: 24px;padding-top: 5px">civil:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #388e3c"> <%= civil_num %></h2>
                  <% end %>
                  <% if cobranza_num == 3 && cobranza_num <4 %>
                    <h2 style="font-size: 24px;padding-top: 5px">cobranza:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #fbc02d"> <%= cobranza_num %></h2>
                  <% end %>
                  <% if cobranza_num > 4 %>
                    <h2 style="font-size: 24px;padding-top: 5px">cobranza:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #b71c1c"> <%= cobranza_num %></h2>
                  <% end %>
                  <% if cobranza_num <= 2 %>
                    <h2 style="font-size: 24px;padding-top: 5px">cobranza:</h2><h2 style="font-size: 24px;padding-top: 5px; color: #388e3c"> <%= cobranza_num %></h2>
                  <% end %>

                <div class="btn-card" >
                  <%= link_to "Revisar", consultation_path(consultation) %>
                </div>

              </div>
            </div>

      <% end %>

  </div>

</div>

app/views/consultations/new.html.erb
<div class="container devise-form">
<h2>Consular un RUT: </h2>

    <%= simple_form_for(@consultation,url: consultations_path, method: :post) do |f| %>
          <h3><%= f.input :rut%></h3>
          <h3> <%= f.hint 'Poner en Formato: 12345678-9' %></h3>
          <div>
          <h2> <%= f.button :submit, "Buscar", class: "btn-log"%></h2>
          </div>
       <% end %>

</div>

app/views/consultations/show.html.erb
<div id="display">
  <div class="vertical">
    <%= render "shared/vertical" %>
  </div>

  <div class="container" style="margin-left: 5px; ">


  <% @demandas.each do |demanda| %>

    <div class="card-product">

    <div class="card-product-infos" style="width: 400px;">
      <% if demanda.tipo.upcase == 'CIVIL'  %>
        <h1>Civil</h1>
      <% elsif demanda.tipo.upcase == 'LABORAL'  %>
        <h1>Laboral</h1>
      <% elsif demanda.tipo.upcase == 'COBRANZA'  %>
        <h1>Cobranza</h1>
      <% end %>
    </div>

    <div class="card-product-infos" style="width: 600px;">
      <h6><strong>Procedimiento:</strong> <%= demanda.proc %></h6>
      <h6><strong>Tribunal:</strong> <%=  demanda.tribunal %></h6>
      <h6><strong>Estado:</strong> <%= demanda.estado %></h6>

    </div>


    <div class="card-product-infos" style="width: 400px;">

      <h6><strong>Rol:</strong> <%= demanda.rol %> </h6>
      <h6><strong>Etapa: </strong><%= demanda.etapa %></h6>
      <h6><strong>Fecha ingreso: </strong><%=  demanda.fechaingreso.to_date %></h6>

    </div>


    <div id="options" data-controller="visibility">

      <div class="card-product-infos" style="width: 400px;" >
        <h3 data-visibility-target="hideable" hidden >Litigantes:</h3>
        <% demanda.litigantes.each do |litigante| %>
        <h6 data-visibility-target="hideable" hidden > <%= "#{litigante.nombre.upcase} -- #{ litigante.sujeto}"%> </h6>
        <% end %>
      </div>


      <div class="card-product-infos">
        <button data-action="visibility#toggleTargets"> <i class="fa-sharp fa-solid fa-eye"></i></button>
        <a class="btn-link" href="<%=  demanda.link %>" style="width: 220px;font-weight: bolder;font-family: 'DM Sans', sans-serif;font-size: 24px;text-decoration: none;padding-left: 50px;padding-right: 50px;margin-left: 0px;"> link</a>
      </div>

    </div>




    </div>

  <% end %>


  </div>

</div>