config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :consultations, only:[:new,:create, :index, :show] do
    resources :litigantes, only:[:index]
  end
  resources :contactos, only:[:new, :create]
  resources :suscriptions, only: [:index, :show]


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

<div class="footer-copyright">
    © 2022 JPTProgram, S.P.A Chile. All Rights reserved
  </div>

  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="height: 60px;" >
  <div class="container-fluid" style="height: 40px;" >
    <a class="navbar-brand" href="/" style="height: 150px;" >
      <h1><span id="an">An</span><span id="fin">Fin</span></h1>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <% unless user_signed_in? %>

            <li class="nav-item active">

              <h3><%= link_to "Registrarte", new_user_registration_path, class: "nav-link" %></h3>
            </li>

            <li class="nav-item">
              <h3><%= link_to "Entrar", new_user_session_path, class: "nav-link" %></h3>
            </li>

          <% else %>
            <% if current_user.admin %>

              <li class="nav-item active">

              <h3><%= link_to "Admin", admin_root_path, class: "nav-link" %></h3>
              </li>
            <% end %>

            <li class="nav-item active ">
              <h3><%= link_to "Membresía", suscriptions_path, class: "nav-link" %></h3>
            </li>


            <li class="nav-item active">
              <h3><%= link_to "Nuevo-Rut", new_consultation_path, class: "nav-link" %></h3>
            </li>

            <li class="nav-item active">

              <h3><%= link_to "Consultas", consultations_path, class: "nav-link" %></h3>
            </li>


            <li class="nav-item active">
              <h3><%= link_to "Perfil", edit_user_registration_path, class: "nav-link" %></h3>
            </li>

            <li class="nav-item active">

              <h3> <%= link_to "Salir", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %> </h3>
            </li>
          <% end %>

          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/shared/_vertical.html.erb
      <ul>
            <div id="spacer">
            </div>

            <li><a href="/">
              <i class="fas fa-home"></i>
              <%# Home %>
              </a></li>

            <li><a href="/users/edit">
              <i class="fas fa-user"></i>
            <%# User %>
            </a></li>

            <li><a href="/contactos/new">
            <i class="fas fa-solid fa-message"></i>
              <%# Contact %>
              </a></li>

            <li><a href="/admin">
            <i class="fas fa-solid fa-gear"></i>
              <%# Config %>
              </a></li>


      </ul>