config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :consultations, only:[:new,:create, :index, :show] do
    resources :litigantes, only:[:index]
  end
  resources :contactos, only:[:new, :create]
  resources :suscriptions, only: [:index, :show]


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/pages/home.html.erb
  <section id="header" style="height: 850px;">
    <article>

          <div data-controller="scroll-reveal" style="margin-top: 220px">
            <h1 data-scroll-reveal-target="item" class="reveal" style="font-family: 'DM Sans', sans-serif;">Análisis Legal en <strong>un click</strong></h1>
            <h3 data-scroll-reveal-target="item" class="reveal" data-delay="250ms" style="font-family: 'DM Sans', sans-serif;">Te entregamos el background check <strong>mas completo</strong> del mercado, dandote una poderosa herramienta para evitar riesgos laborales, <strong>explicado</strong> de manera <span>sencilla</span> usando la informacion displonible en distintos sitios web de transparencia en el sistema judicial, la cual es de  <strong>utiludad publica.</strong></h3>
          </div>


        <div class="buttons" >
          <% unless user_signed_in? %>
          <%= link_to "Registrate", new_user_registration_path, class: "btn-alert" %>
          <%= link_to "Contactanos", new_contacto_path, class: "btn-contacto" %>
          <% end %>
          <% if user_signed_in? %>
          <%= link_to "Haz una consulta", new_consultation_path, class: "btn-soft" %>
          <% end %>

        </div>
      </article>
    </section>

    <section id="analiza" style="height: 1200px;">

      <article>
        <div data-controller="scroll-reveal" style="margin-top: 100px">
          <h2 data-scroll-reveal-target="item" class="reveal" data-delay="400ms" style="font-family: 'DM Sans', sans-serif;"> Analiza a tus clientes con los datos mas importantes para tu área de Recursos Humanos</h2>
          <h3 data-scroll-reveal-target="item" class="reveal" data-delay="400ms" style="font-family: 'DM Sans', sans-serif;margin-left: 20px; ">Seleccionamos 3 variables predictoras de riesgo en laboral, para reducir la probabilidad de impactos laborales</h3>
        </div>

      </article>

          <div data-controller="scroll-reveal"   style="margin-left: 200px;">
            <img src="https://res.cloudinary.com/dp693fkkc/image/upload/v1668313286/AnFin/esqema_dljfnf.png" alt="esquema" data-scroll-reveal-target="item" class="reveal" data-delay="500ms">
          </div>

    </section>
    <section id="modelo" style="height: 100px;">
      <article>

          <div data-controller="scroll-reveal" style="margin-top: 220px">
            <h1 data-scroll-reveal-target="item" class="reveal" style="font-family: 'DM Sans', sans-serif;"> Construido con modelo <strong>predictivo</strong> el cual te entregara un resumen de fuentes de <strong>riesgo</strong></h1>
            <h3 data-scroll-reveal-target="item" class="reveal" data-delay="250ms" style="font-family: 'DM Sans', sans-serif;">Aparte, las demandas se entreegan en formatos PDF para poder conocer más a fondo a su cliente y asi tomar su desicion de mejor manera</h3>
          </div>

      </article>
    </section>
    <section id="algoritmo" style="height: 300px;">
        <div style="height: 300px;">

          <div data-controller="scroll-reveal">
            <h1 data-scroll-reveal-target="item" class="reveal" style="font-family: 'DM Sans', sans-serif;"> Nuestros algoritmos a <strong>tu medida</strong>.</strong></h1>
            <h3 data-scroll-reveal-target="item" class="reveal" data-delay="250ms" style="font-family: 'DM Sans', sans-serif;">Entendemos que cada persona tiene distintos factores de riesgo legal, asi que con nuestro algoritmo clasificamos las variables de mayor importancia: <strong>civil, legal y laboral</h3>
         </div>

        </div>
        <div class="container">
          <img src="https://res.cloudinary.com/dp693fkkc/image/upload/v1668313286/AnFin/hash_sncbnk.png" alt="esquema">
        </div>
    </section>

<%= render "shared/footer" %>